SELECT *
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = N'SalesPerson'
FROM SYS.COLUMNS
WHERE OBJECT_ID = OBJECT_ID('SALES.SalesPerson')

SELECT * FROM SYS.TABLES WHERE NAME='SalesPerson'
SELECT * FROM SYS.OBJECTS WHERE NAME='SalesPerson'

SELECT OBJECT_ID('SALES.SalesPerson','U')

IF OBJECT_ID('SalesPerson', 'U') IS NOT NULL 
BEGIN
SELECT 'A'
END
ELSE BEGIN
SELECT 'B'
END


IF OBJECT_ID('SALES.SalesPerson', 'U') IS NOT NULL 
BEGIN
SELECT 'A'
END
ELSE BEGIN
SELECT 'B'
END


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_NAME = N'SalesPerson')
BEGIN
SELECT 'A'
END
ELSE BEGIN
SELECT 'B'
END


IF EXISTS(SELECT 1 FROM sys.Objects 
    WHERE  Object_id = OBJECT_ID(N'SALES.SalesPerson') 
           AND Type = N'U')
BEGIN
SELECT 'A'
END
ELSE BEGIN
SELECT 'B'
END
	   
IF EXISTS(SELECT 1 FROM sys.Tables 
WHERE  Name = N'SalesPerson')
BEGIN
SELECT 'A'
END
ELSE BEGIN
SELECT 'B'
END



